"""Facade panel generator.

Triggered by the slab curves model. Fetches curves, sends them to
Rhino Compute running the Grasshopper definition, and publishes the
resulting mesh panels to the facade panels model.
"""

import json
import logging

import requests
import rhino3dm
from compute_rhino3d import Grasshopper, Util
from pydantic import Field, SecretStr
from speckle_automate import (
    AutomateBase,
    AutomationContext,
    execute_automate_function,
)
from specklepy.objects import Base

from flatten import flatten_base

logger = logging.getLogger(__name__)

CURVE_TYPES = (
    "Objects.Geometry.Curve",
    "Objects.Geometry.Polyline",
    "Objects.Geometry.Line",
    "Objects.Geometry.Arc",
    "Objects.Geometry.Circle",
    "Objects.Geometry.Ellipse",
    "Objects.Geometry.Polycurve",
)


class FunctionInputs(AutomateBase):
    """Inputs for the facade panel generation function."""

    compute_url: str = Field(
        default="https://compute8.iaac.net/",
        title="Rhino Compute URL",
        description="Base URL of your Rhino Compute server (include trailing slash).",
    )
    compute_api_key: SecretStr = Field(
        title="Rhino Compute API Key",
        description="API key for the Rhino Compute server.",
    )
    grasshopper_definition_url: str = Field(
        title="Grasshopper Definition URL",
        description=(
            "Public URL to your .gh file. "
            "e.g. https://raw.githubusercontent.com/etmegla/"
            "Team-03-2-facade-panels/main/Team03.2_Final_Assignment.gh"
        ),
    )
    gh_input_name: str = Field(
        default="Curves",
        title="GH Input Parameter Name",
        description="Nickname of the Grasshopper input that receives the curves.",
    )
    gh_output_name: str = Field(
        default="Mesh",
        title="GH Output Parameter Name",
        description="Nickname of the Grasshopper output that returns the mesh panels.",
    )
    target_model_id: str = Field(
        title="Target Model ID",
        description=(
            "Speckle model ID to publish the facade panels into. "
            "Find it in the URL: /projects/.../models/<model-id>"
        ),
    )
    version_message: str = Field(
        default="Facade panels generated by Automate",
        title="Version Message",
        description="Commit message for the new version in the target model.",
    )


def _get_children(obj: Base) -> list:
    """Return child objects from any known container attribute."""
    for attr in ("elements", "@elements", "objects", "@objects"):
        children = getattr(obj, attr, None)
        if children and isinstance(children, list):
            return children
    return []


def _extract_all_curves(obj: Base, collected: list) -> None:
    """Recursively collect all curve objects from the version root."""
    speckle_type = getattr(obj, "speckle_type", "")
    if any(speckle_type.startswith(ct) for ct in CURVE_TYPES):
        collected.append(obj)
        return
    for child in _get_children(obj):
        if isinstance(child, Base):
            _extract_all_curves(child, collected)


def _speckle_to_rhino_json(obj: Base) -> dict | None:
    """Convert a Speckle curve object to a rhino3dm-encoded JSON dict."""
    st = getattr(obj, "speckle_type", "")

    if "Polyline" in st or "Line" in st:
        pts = getattr(obj, "value", None)
        if pts and len(pts) >= 6:
            pl = rhino3dm.Polyline()
            for i in range(0, len(pts), 3):
                pl.Add(pts[i], pts[i + 1], pts[i + 2])
            return json.loads(pl.ToPolylineCurve().Encode())

    if "Curve" in st:
        degree = getattr(obj, "degree", 3)
        points = getattr(obj, "points", [])
        knots = getattr(obj, "knots", [])
        weights = getattr(obj, "weights", None)
        rational = weights is not None and len(weights) == len(points) // 3

        if points and knots:
            nc = rhino3dm.NurbsCurve(3, rational, degree + 1, len(points) // 3)
            for i in range(len(points) // 3):
                x, y, z = points[3*i], points[3*i+1], points[3*i+2]
                w = weights[i] if rational else 1.0
                nc.Points[i] = rhino3dm.Point4d(x, y, z, w)
            for i, k in enumerate(knots):
                nc.Knots[i] = k
            return json.loads(nc.Encode())

    return None


def _fetch_gh_definition(url: str) -> list[int]:
    """Download the .gh file and return it as a list of ints for compute SDK."""
    logger.info("Fetching GH definition from %s", url)
    r = requests.get(url, timeout=60)
    r.raise_for_status()
    return list(r.content)


def _run_grasshopper(
    gh_definition: list[int],
    curve_jsons: list[dict],
    inputs: FunctionInputs,
) -> dict:
    """Send curves to Rhino Compute and return the raw result dict."""
    Util.url = inputs.compute_url
    Util.apiKey = inputs.compute_api_key.get_secret_value()

    curve_tree = Grasshopper.DataTree(inputs.gh_input_name)
    for i, cj in enumerate(curve_jsons):
        curve_tree.append([i], [json.dumps(cj)])

    return Grasshopper.EvaluateDefinition(gh_definition, [curve_tree])


def _parse_mesh_output(gh_result: dict, output_name: str) -> list[Base]:
    """Extract mesh geometry from the GH result and wrap as Speckle Base objects."""
    panels: list[Base] = []

    for entry in gh_result.get("values", []):
        if entry.get("ParamName") != output_name:
            continue
        for _path, items in entry.get("InnerTree", {}).items():
            for item in items:
                raw = item.get("data", "")
                if not raw:
                    continue
                try:
                    geo_dict = json.loads(raw) if isinstance(raw, str) else raw
                    rh_obj = rhino3dm.CommonObject.Decode(geo_dict)
                    panel = Base()
                    panel["speckle_type"] = "Objects.Geometry.Mesh"
                    panel["rhinoData"] = geo_dict
                    panel["generatedBy"] = "facade-panel-automate"
                    if hasattr(rh_obj, "Faces"):
                        panel["vertexCount"] = len(rh_obj.Vertices)
                        panel["faceCount"] = rh_obj.Faces.Count
                    panels.append(panel)
                except Exception as e:
                    logger.warning("Could not decode mesh object: %s", e)

    return panels


def automate_function(
    automate_context: AutomationContext,
    function_inputs: FunctionInputs,
) -> None:
    """Fetch curves from slab curves model, run GH, publish panels."""

    # 1. Receive the trigger model (slab curves)
    version_root = automate_context.receive_version()

    # 2. Extract all curves
    curve_objects: list[Base] = []
    _extract_all_curves(version_root, curve_objects)

    if not curve_objects:
        automate_context.mark_run_failed(
            "No curve objects found in the trigger model."
        )
        return

    logger.info("Found %d curves.", len(curve_objects))

    # 3. Convert Speckle curves → Rhino JSON
    curve_jsons = []
    skipped = []
    for obj in curve_objects:
        rj = _speckle_to_rhino_json(obj)
        if rj is not None:
            curve_jsons.append(rj)
        else:
            skipped.append(obj)

    if skipped:
        automate_context.attach_warning_to_objects(
            category="Conversion",
            affected_objects=skipped,
            message="Could not convert to Rhino format — skipped.",
        )

    if not curve_jsons:
        automate_context.mark_run_failed(
            "All curves failed Rhino conversion. "
            "Check that the slab curves model contains Polyline or NURBS curves."
        )
        return

    logger.info("Converted %d / %d curves.", len(curve_jsons), len(curve_objects))

    # 4. Fetch GH definition
    try:
        gh_definition = _fetch_gh_definition(
            function_inputs.grasshopper_definition_url
        )
    except Exception as exc:
        automate_context.mark_run_exception(
            f"Failed to download Grasshopper definition: {exc}"
        )
        return

    # 5. Run Rhino Compute
    logger.info("Sending %d curves to Rhino Compute ...", len(curve_jsons))
    try:
        gh_result = _run_grasshopper(gh_definition, curve_jsons, function_inputs)
    except Exception as exc:
        automate_context.mark_run_exception(
            f"Rhino Compute call failed: {exc}"
        )
        return

    if gh_result.get("errors"):
        automate_context.mark_run_failed(
            f"Grasshopper errors: {'; '.join(str(e) for e in gh_result['errors'])}"
        )
        return

    # 6. Parse mesh output
    panel_objects = _parse_mesh_output(gh_result, function_inputs.gh_output_name)

    if not panel_objects:
        automate_context.mark_run_failed(
            f"Grasshopper ran but returned no geometry on output "
            f"'{function_inputs.gh_output_name}'. "
            "Check the GH Output Parameter Name matches your component nickname exactly."
        )
        return

    logger.info("Generated %d panel mesh objects.", len(panel_objects))

    # 7. Publish to facade panels model
    root = Base()
    root["@elements"] = panel_objects
    root["panelCount"] = len(panel_objects)
    root["curveCount"] = len(curve_jsons)
    root["sourceModelId"] = (
        automate_context.automation_run_data.triggers[0].payload.model_id
    )

    automate_context.create_new_version_in_project(
        root_object=root,
        model_id=function_inputs.target_model_id,
        version_message=function_inputs.version_message,
    )

    automate_context.attach_success_to_objects(
        category="Facade Panels",
        affected_objects=curve_objects,
        message=(
            f"Generated {len(panel_objects)} mesh panels from "
            f"{len(curve_jsons)} curves → model '{function_inputs.target_model_id}'"
        ),
        metadata={
            "panelCount": len(panel_objects),
            "curveCount": len(curve_jsons),
        },
    )

    automate_context.mark_run_success(
        f"Generated {len(panel_objects)} facade panels from {len(curve_jsons)} "
        f"curves and published to model '{function_inputs.target_model_id}'."
    )


if __name__ == "__main__":
    execute_automate_function(automate_function, FunctionInputs)