"""Facade panel generator.

Triggered by the slab curves model. Fetches curves, sends them to
Rhino Compute running the Grasshopper definition, and publishes the
resulting mesh panels to the facade panels model.
"""

import json
import logging
import sys
from base64 import b64decode
from collections.abc import Iterable
from urllib.parse import urlparse

import requests
from pydantic import Field, SecretStr
from speckle_automate import (
    AutomateBase,
    AutomationContext,
    execute_automate_function,
)
from specklepy.objects import Base

from flatten import flatten_base

logger = logging.getLogger(__name__)

try:
    import rhino3dm
except Exception:  # pragma: no cover - depends on local env
    rhino3dm = None

try:
    from compute_rhino3d import Grasshopper, Util
except Exception:  # pragma: no cover - depends on local env
    Grasshopper = None
    Util = None

CURVE_TYPES = (
    "Objects.Geometry.Curve",
    "Objects.Geometry.Polyline",
    "Objects.Geometry.Line",
    "Objects.Geometry.Arc",
    "Objects.Geometry.Circle",
    "Objects.Geometry.Ellipse",
    "Objects.Geometry.Polycurve",
)


class FunctionInputs(AutomateBase):
    """Inputs for the facade panel generation function."""

    compute_url: str = Field(
        default="https://compute8.iaac.net/",
        title="Rhino Compute URL",
        description="Base URL of your Rhino Compute server (include trailing slash).",
    )
    compute_api_key: SecretStr = Field(
        title="Rhino Compute API Key",
        description="API key for the Rhino Compute server.",
    )
    grasshopper_definition_url: str = Field(
        title="Grasshopper Definition URL",
        description=(
            "Public URL to your .gh file. "
            "e.g. https://raw.githubusercontent.com/etmegla/"
            "Team-03-2-facade-panels/main/Team03.2_Final_Assignment.gh"
        ),
    )
    github_token: SecretStr | None = Field(
        default=None,
        title="GitHub Token (optional)",
        description=(
            "Optional token for private GitHub repos. "
            "If set, used to fetch the .gh file via authenticated requests."
        ),
    )
    gh_input_name: str = Field(
        default="Curves",
        title="GH Input Parameter Name",
        description="Nickname of the Grasshopper input that receives the curves.",
    )
    gh_output_name: str = Field(
        default="Mesh",
        title="GH Output Parameter Name",
        description="Nickname of the Grasshopper output that returns the mesh panels.",
    )
    layer_name: str = Field(
        default="",
        title="Layer Name Filter",
        description=(
            "Optional Rhino layer or collection name filter (e.g. 'Slab Curves' or "
            "'3D-Model::Structure::Floor Plate Curve'). Leave empty to use all curves."
        ),
    )
    strict_layer_match: bool = Field(
        default=False,
        title="Strict Layer Match",
        description=(
            "If true and layer_name is set, fail when no curves are found in that "
            "layer. If false, fallback to all curves."
        ),
    )
    target_model_id: str = Field(
        title="Target Model ID",
        description=(
            "Speckle model ID to publish the facade panels into. "
            "Find it in the URL: /projects/.../models/<model-id>"
        ),
    )
    version_message: str = Field(
        default="Facade panels generated by Automate",
        title="Version Message",
        description="Commit message for the new version in the target model.",
    )


def _get_children(obj: Base) -> list:
    """Return child objects from any known container attribute."""
    for attr in ("elements", "@elements", "objects", "@objects"):
        children = getattr(obj, attr, None)
        if children and isinstance(children, list):
            return children
    return []


def _extract_all_curves(obj: Base, collected: list) -> None:
    """Recursively collect all curve objects from the version root."""
    speckle_type = getattr(obj, "speckle_type", "")
    if any(speckle_type.startswith(ct) for ct in CURVE_TYPES):
        collected.append(obj)
        return
    for child in _get_children(obj):
        if isinstance(child, Base):
            _extract_all_curves(child, collected)


def _extract_layer_candidates(obj: Base) -> set[str]:
    """Collect possible layer labels attached to an object or collection node."""
    candidates: set[str] = set()

    for attr in ("layer", "Layer", "name"):
        value = getattr(obj, attr, None)
        if isinstance(value, str) and value.strip():
            candidates.add(value.strip())

    props = getattr(obj, "properties", None)
    if props:
        for attr in ("layer", "Layer", "name"):
            value = getattr(props, attr, None)
            if isinstance(value, str) and value.strip():
                candidates.add(value.strip())

    return candidates


def _match_layer_candidates(candidates: Iterable[str], layer_filter: str) -> bool:
    """Return True when any candidate matches the requested layer (path-aware)."""
    if not layer_filter:
        return True

    normalized_filter = layer_filter.strip()
    filter_leaf = normalized_filter.split("::")[-1].strip()

    for candidate in candidates:
        normalized_candidate = candidate.strip()
        if not normalized_candidate:
            continue

        if normalized_candidate == normalized_filter:
            return True

        candidate_leaf = normalized_candidate.split("::")[-1].strip()
        if candidate_leaf == filter_leaf:
            return True

        if normalized_candidate.endswith(f"::{normalized_filter}"):
            return True

        if normalized_filter.endswith(f"::{normalized_candidate}"):
            return True

    return False


def _iter_base_with_inherited_layers(
    root: Base,
    inherited_layers: set[str] | None = None,
) -> Iterable[tuple[Base, set[str]]]:
    """Traverse the tree and carry parent layer labels to descendants."""
    inherited = inherited_layers or set()
    current_layers = _extract_layer_candidates(root)
    effective_layers = inherited | current_layers

    yield root, effective_layers

    for child in _get_children(root):
        if isinstance(child, Base):
            yield from _iter_base_with_inherited_layers(child, effective_layers)


def _rhino_encode_to_dict(encoded: object) -> dict | None:
    """Normalize rhino3dm Encode() output to a Python dict."""
    if isinstance(encoded, dict):
        return encoded

    if isinstance(encoded, (str, bytes, bytearray)):
        parsed = json.loads(encoded)
        return parsed if isinstance(parsed, dict) else None

    return None


def _speckle_to_rhino_json(obj: Base) -> dict | None:
    """Convert a Speckle curve object to a rhino3dm-encoded JSON dict."""
    if rhino3dm is None:
        raise RuntimeError("rhino3dm is not installed in this environment")

    st = getattr(obj, "speckle_type", "")

    if "Polyline" in st or "Line" in st:
        pts = getattr(obj, "value", None)
        if pts and len(pts) >= 6:
            pl = rhino3dm.Polyline()
            for i in range(0, len(pts), 3):
                pl.Add(pts[i], pts[i + 1], pts[i + 2])
            encoded = pl.ToPolylineCurve().Encode()
            return _rhino_encode_to_dict(encoded)

    if "Curve" in st:
        degree = getattr(obj, "degree", 3)
        points = getattr(obj, "points", [])
        knots = getattr(obj, "knots", [])
        weights = getattr(obj, "weights", None)
        rational = weights is not None and len(weights) == len(points) // 3

        if points and knots:
            point_count = len(points) // 3
            nc = rhino3dm.NurbsCurve(3, rational, degree + 1, point_count)
            for i in range(point_count):
                x, y, z = points[3*i], points[3*i+1], points[3*i+2]
                w = weights[i] if rational else 1.0
                nc.Points[i] = rhino3dm.Point4d(x, y, z, w)
            rhino_knot_count = point_count + degree - 1
            for i in range(min(len(knots), rhino_knot_count)):
                nc.Knots[i] = knots[i]
            return _rhino_encode_to_dict(nc.Encode())

    return None

def _raw_url_to_github_contents_api(url: str) -> str | None:
    """Convert raw/blob GitHub file URL to GitHub Contents API URL."""
    parsed = urlparse(url)
    parts = [p for p in parsed.path.split("/") if p]

    if parsed.netloc == "raw.githubusercontent.com":
        if len(parts) < 4:
            return None
        owner, repo, ref = parts[0], parts[1], parts[2]
        file_path = "/".join(parts[3:])
    elif parsed.netloc == "github.com":
        # /owner/repo/blob/<ref>/<path>
        if len(parts) < 5 or parts[2] != "blob":
            return None
        owner, repo, ref = parts[0], parts[1], parts[3]
        file_path = "/".join(parts[4:])
    else:
        return None

    return f"https://api.github.com/repos/{owner}/{repo}/contents/{file_path}?ref={ref}"


def _normalize_github_file_url(url: str) -> str:
    """Normalize GitHub blob URLs to raw URLs for direct file download."""
    parsed = urlparse(url)
    if parsed.netloc != "github.com":
        return url

    parts = [p for p in parsed.path.split("/") if p]
    if len(parts) < 5 or parts[2] != "blob":
        return url

    owner, repo, ref = parts[0], parts[1], parts[3]
    file_path = "/".join(parts[4:])
    return f"https://raw.githubusercontent.com/{owner}/{repo}/{ref}/{file_path}"


def _fetch_gh_definition(url: str, github_token: SecretStr | None = None) -> list[int]:
    """Download the .gh file and return it as a list of ints for compute SDK."""
    normalized_url = _normalize_github_file_url(url)
    logger.info("Fetching GH definition from %s", normalized_url)

    headers: dict[str, str] = {}
    if github_token is not None:
        token = github_token.get_secret_value().strip()
        if token:
            headers["Authorization"] = f"Bearer {token}"

    response = requests.get(normalized_url, timeout=60, headers=headers)
    if response.ok:
        return list(response.content)

    # For private GitHub repos, raw URL often returns 404 without auth context;
    # try GitHub contents API when URL points to raw.githubusercontent.com.
    api_url = _raw_url_to_github_contents_api(normalized_url)
    if api_url and "Authorization" in headers:
        api_headers = {
            "Authorization": headers["Authorization"],
            "Accept": "application/vnd.github+json",
        }
        api_response = requests.get(api_url, timeout=60, headers=api_headers)
        api_response.raise_for_status()
        payload = api_response.json()
        encoded = payload.get("content", "")
        if not encoded:
            raise RuntimeError("GitHub contents API response did not include file content")
        return list(b64decode(encoded))

    response.raise_for_status()
    return []


def _run_grasshopper(
    gh_definition: list[int],
    curve_jsons: list[dict],
    inputs: FunctionInputs,
) -> dict:
    """Send curves to Rhino Compute and return the raw result dict."""
    if Grasshopper is None or Util is None:
        raise RuntimeError("compute-rhino3d is not installed in this environment")

    Util.url = inputs.compute_url
    Util.apiKey = inputs.compute_api_key.get_secret_value()

    curve_tree = Grasshopper.DataTree(inputs.gh_input_name)
    for i, cj in enumerate(curve_jsons):
        curve_tree.append([i], [json.dumps(cj)])

    return Grasshopper.EvaluateDefinition(gh_definition, [curve_tree])


def _parse_mesh_output(gh_result: dict, output_name: str) -> list[Base]:
    """Extract mesh geometry from the GH result and wrap as Speckle Base objects."""
    panels: list[Base] = []

    for entry in gh_result.get("values", []):
        if entry.get("ParamName") != output_name:
            continue
        for _path, items in entry.get("InnerTree", {}).items():
            for item in items:
                raw = item.get("data", "")
                if not raw:
                    continue
                try:
                    geo_dict = json.loads(raw) if isinstance(raw, str) else raw
                    panel = Base()
                    panel["speckle_type"] = "Objects.Geometry.Mesh"
                    panel["rhinoData"] = geo_dict
                    panel["generatedBy"] = "facade-panel-automate"
                    if rhino3dm is not None:
                        rh_obj = rhino3dm.CommonObject.Decode(geo_dict)
                        if hasattr(rh_obj, "Faces"):
                            panel["vertexCount"] = len(rh_obj.Vertices)
                            panel["faceCount"] = rh_obj.Faces.Count
                    panels.append(panel)
                except Exception as e:
                    logger.warning("Could not decode mesh object: %s", e)

    return panels


def automate_function(
    automate_context: AutomationContext,
    function_inputs: FunctionInputs,
) -> None:
    """Fetch curves from slab curves model, run GH, publish panels."""

    # 1. Receive the trigger model (slab curves)
    version_root = automate_context.receive_version()

    # 2. Extract all curves (with inherited layer context)
    curves_with_layers = [
        (obj, layers)
        for obj, layers in _iter_base_with_inherited_layers(version_root)
        if any(getattr(obj, "speckle_type", "").startswith(ct) for ct in CURVE_TYPES)
    ]
    curve_objects = [obj for obj, _ in curves_with_layers]

    if not curve_objects:
        automate_context.mark_run_failed(
            "No curve objects found in the trigger model."
        )
        return

    layer_filter = function_inputs.layer_name.strip()
    if layer_filter:
        filtered_curves = [
            obj
            for obj, layers in curves_with_layers
            if _match_layer_candidates(layers, layer_filter)
        ]

        if filtered_curves:
            curve_objects = filtered_curves
            logger.info(
                "Found %d curves total; %d matched layer filter '%s'.",
                len(curves_with_layers),
                len(curve_objects),
                layer_filter,
            )
        elif function_inputs.strict_layer_match:
            automate_context.mark_run_failed(
                f"No curves matched layer filter '{layer_filter}'. "
                "Set Strict Layer Match to false to fallback to all curves."
            )
            return
        else:
            logger.warning(
                "No curves matched layer filter '%s'. Falling back to all %d curves.",
                layer_filter,
                len(curve_objects),
            )
    else:
        logger.info("Found %d curves.", len(curve_objects))

    # 3. Convert Speckle curves → Rhino JSON
    curve_jsons = []
    skipped = []
    for obj in curve_objects:
        rj = _speckle_to_rhino_json(obj)
        if rj is not None:
            curve_jsons.append(rj)
        else:
            skipped.append(obj)

    if skipped:
        automate_context.attach_warning_to_objects(
            category="Conversion",
            affected_objects=skipped,
            message="Could not convert to Rhino format — skipped.",
        )

    if not curve_jsons:
        automate_context.mark_run_failed(
            "All curves failed Rhino conversion. "
            "Check that the slab curves model contains Polyline or NURBS curves."
        )
        return

    logger.info("Converted %d / %d curves.", len(curve_jsons), len(curve_objects))

    # 4. Fetch GH definition
    try:
        gh_definition = _fetch_gh_definition(
            function_inputs.grasshopper_definition_url,
            function_inputs.github_token,
        )
    except Exception as exc:
        automate_context.mark_run_exception(
            f"Failed to download Grasshopper definition: {exc}"
        )
        return

    # 5. Run Rhino Compute
    logger.info("Sending %d curves to Rhino Compute ...", len(curve_jsons))
    try:
        gh_result = _run_grasshopper(gh_definition, curve_jsons, function_inputs)
    except Exception as exc:
        automate_context.mark_run_exception(
            f"Rhino Compute call failed: {exc}"
        )
        return

    if gh_result.get("errors"):
        automate_context.mark_run_failed(
            f"Grasshopper errors: {'; '.join(str(e) for e in gh_result['errors'])}"
        )
        return

    # 6. Parse mesh output
    panel_objects = _parse_mesh_output(gh_result, function_inputs.gh_output_name)

    if not panel_objects:
        automate_context.mark_run_failed(
            f"Grasshopper ran but returned no geometry on output "
            f"'{function_inputs.gh_output_name}'. "
            "Check the GH Output Parameter Name matches your component nickname exactly."
        )
        return

    logger.info("Generated %d panel mesh objects.", len(panel_objects))

    # 7. Publish to facade panels model
    root = Base()
    root["@elements"] = panel_objects
    root["panelCount"] = len(panel_objects)
    root["curveCount"] = len(curve_jsons)
    root["sourceModelId"] = (
        automate_context.automation_run_data.triggers[0].payload.model_id
    )

    automate_context.create_new_version_in_project(
        root_object=root,
        model_id=function_inputs.target_model_id,
        version_message=function_inputs.version_message,
    )

    automate_context.attach_success_to_objects(
        category="Facade Panels",
        affected_objects=curve_objects,
        message=(
            f"Generated {len(panel_objects)} mesh panels from "
            f"{len(curve_jsons)} curves → model '{function_inputs.target_model_id}'"
        ),
        metadata={
            "panelCount": len(panel_objects),
            "curveCount": len(curve_jsons),
        },
    )

    automate_context.mark_run_success(
        f"Generated {len(panel_objects)} facade panels from {len(curve_jsons)} "
        f"curves and published to model '{function_inputs.target_model_id}'."
    )


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(
            "Run with Speckle Automate runtime arguments.\n"
            "Local checks: pytest\n"
            "Automate shape: python -u main.py run <automationRunDataJson> <functionInputsJson> <token>"
        )
        raise SystemExit(0)

    execute_automate_function(automate_function, FunctionInputs)