"""Facade panel generator: fetches curves from Speckle, runs Grasshopper via
Rhino Compute, and publishes the resulting facade panels to a new Speckle model."""

import json
import logging
import tempfile
from enum import Enum
from pathlib import Path

import requests
import rhino3dm
from compute_rhino3d import Grasshopper, Util
from pydantic import Field, SecretStr
from speckle_automate import (
    AutomateBase,
    AutomationContext,
    execute_automate_function,
)
from specklepy.objects import Base
from specklepy.objects.geometry import Mesh, Point, Polyline, Curve, Brep

from flatten import flatten_base

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Input schema — generates the web form in the Speckle Automate UI
# ---------------------------------------------------------------------------

class PanelType(str, Enum):
    FLAT = "flat"
    FOLDED = "folded"
    PERFORATED = "perforated"


class FunctionInputs(AutomateBase):
    """Configuration for the facade panel generation function."""

    # Rhino Compute connection
    compute_url: str = Field(
        default="https://compute8.iaac.net/",
        title="Rhino Compute URL",
        description="Base URL of your Rhino Compute server (include trailing slash).",
    )
    compute_api_key: SecretStr = Field(
        title="Rhino Compute API Key",
        description="API key for the Rhino Compute server.",
    )

    # Grasshopper definition
    grasshopper_definition_url: str = Field(
        title="Grasshopper Definition URL",
        description=(
            "Publicly reachable URL to your .gh file "
            "(e.g. a raw GitHub URL or a file server path)."
        ),
    )

    # Curve filter — which objects from the trigger model to use as input
    curve_speckle_type: str = Field(
        default="Objects.Geometry.Curve",
        title="Input Curve Speckle Type",
        description=(
            "speckle_type of the objects in the trigger model that should be "
            "passed to Grasshopper as facade base curves. "
            "Common values: Objects.Geometry.Curve, Objects.Geometry.Polyline, "
            "Objects.Geometry.Line."
        ),
    )

    # Grasshopper input/output parameter names
    gh_curve_input_name: str = Field(
        default="Curves",
        title="GH Input Parameter Name",
        description="Name of the Grasshopper input parameter that receives the curves.",
    )
    gh_panel_output_name: str = Field(
        default="Panels",
        title="GH Output Parameter Name",
        description="Name of the Grasshopper output parameter that returns the panels.",
    )

    # Panel options passed through to Grasshopper
    panel_type: PanelType = Field(
        default=PanelType.FLAT,
        title="Panel Type",
        description="Facade panel geometry type to generate.",
    )
    panel_depth: float = Field(
        default=0.2,
        title="Panel Depth (m)",
        description="Extrusion depth of each panel in metres.",
        gt=0,
    )

    # Output model
    target_model_id: str = Field(
        title="Target Model ID",
        description=(
            "Speckle model ID to publish the generated facade panels into. "
            "Find it in the URL: /projects/.../models/<model-id>"
        ),
    )
    output_version_message: str = Field(
        default="Facade panels generated by Automate",
        title="Output Version Message",
        description="Commit message for the new version in the target model.",
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _setup_compute(inputs: FunctionInputs) -> None:
    """Point the compute-rhino3d SDK at the configured server."""
    Util.url = inputs.compute_url
    Util.apiKey = inputs.compute_api_key.get_secret_value()


def _fetch_gh_definition(url: str) -> bytes:
    """Download the Grasshopper .gh file and return its bytes."""
    logger.info("Fetching Grasshopper definition from %s", url)
    response = requests.get(url, timeout=60)
    response.raise_for_status()
    return response.content


def _speckle_curve_to_rhino_json(obj: Base) -> dict | None:
    """Convert a Speckle curve/polyline/line object to a rhino3dm-compatible
    JSON dict that Grasshopper can decode via CommonObject.decode.

    Returns None if the object cannot be converted.
    """
    st = getattr(obj, "speckle_type", "")

    # --- Polyline ---
    if "Polyline" in st or "Line" in st:
        pts = getattr(obj, "value", None)  # flat list [x,y,z, x,y,z …]
        if pts and len(pts) >= 6:
            rc_polyline = rhino3dm.Polyline()
            for i in range(0, len(pts), 3):
                rc_polyline.Add(pts[i], pts[i + 1], pts[i + 2])
            rc_curve = rc_polyline.ToPolylineCurve()
            return json.loads(rc_curve.Encode())

    # --- NURBS Curve (Speckle stores control points + knots) ---
    if "Curve" in st:
        degree = getattr(obj, "degree", 3)
        points = getattr(obj, "points", [])
        knots = getattr(obj, "knots", [])
        weights = getattr(obj, "weights", None)
        rational = weights is not None and len(weights) == len(points) // 3

        if points and knots:
            rc_nc = rhino3dm.NurbsCurve(3, rational, degree + 1, len(points) // 3)
            for i in range(len(points) // 3):
                x, y, z = points[3 * i], points[3 * i + 1], points[3 * i + 2]
                w = weights[i] if rational else 1.0
                rc_nc.Points[i] = rhino3dm.Point4d(x, y, z, w)
            for i, k in enumerate(knots):
                rc_nc.Knots[i] = k
            return json.loads(rc_nc.Encode())

    return None


def _build_gh_trees(curve_jsons: list[dict], inputs: FunctionInputs) -> list:
    """Wrap curve JSON dicts in Grasshopper DataTree objects ready for compute."""
    curve_tree = Grasshopper.DataTree(inputs.gh_curve_input_name)
    for i, cj in enumerate(curve_jsons):
        curve_tree.append([i], [json.dumps(cj)])

    panel_type_tree = Grasshopper.DataTree("PanelType")
    panel_type_tree.append([0], [inputs.panel_type.value])

    panel_depth_tree = Grasshopper.DataTree("PanelDepth")
    panel_depth_tree.append([0], [inputs.panel_depth])

    return [curve_tree, panel_type_tree, panel_depth_tree]


def _parse_gh_output(res: dict, output_name: str) -> list[Base]:
    """Parse Grasshopper compute results into a list of Speckle Base objects."""
    panels: list[Base] = []

    for value_entry in res.get("values", []):
        if value_entry.get("ParamName") != output_name:
            continue
        for _path, items in value_entry.get("InnerTree", {}).items():
            for item in items:
                data_type = str(item.get("type", ""))
                raw = item.get("data", "")
                if not raw:
                    continue

                if "Geometry" in data_type or "Brep" in data_type or "Mesh" in data_type:
                    geo_dict = json.loads(raw) if isinstance(raw, str) else raw

                    panel = Base()
                    panel.speckle_type = "Objects.Geometry.Mesh"
                    panel["rhinoData"] = geo_dict   # keep raw rhino geometry
                    panel["generatedBy"] = "facade-panel-automate"

                    # Attempt to decode into a proper rhino3dm object for richer data
                    try:
                        rh_obj = rhino3dm.CommonObject.Decode(geo_dict)
                        if hasattr(rh_obj, "Faces"):  # it's a Mesh
                            panel["vertexCount"] = len(rh_obj.Vertices)
                            panel["faceCount"] = rh_obj.Faces.Count
                    except Exception:
                        pass

                    panels.append(panel)

    return panels


# ---------------------------------------------------------------------------
# Main automate function
# ---------------------------------------------------------------------------

def automate_function(
    automate_context: AutomationContext,
    function_inputs: FunctionInputs,
) -> None:
    """Fetch curves from the trigger model, run Grasshopper, publish panels."""

    # ------------------------------------------------------------------
    # 1. Receive the trigger model version
    # ------------------------------------------------------------------
    logger.info("Receiving trigger model version …")
    version_root = automate_context.receive_version()

    # ------------------------------------------------------------------
    # 2. Extract curve objects
    # ------------------------------------------------------------------
    target_type = function_inputs.curve_speckle_type
    curve_objects = [
        obj
        for obj in flatten_base(version_root)
        if getattr(obj, "speckle_type", "").startswith(
            target_type.split(".")[0]  # broad match first
        )
        and target_type.split(".")[-1].lower()
        in getattr(obj, "speckle_type", "").lower()
    ]

    if not curve_objects:
        automate_context.attach_error_to_objects(
            category="Input",
            affected_objects=[version_root],
            message=(
                f"No objects of type '{target_type}' found in the trigger model. "
                "Check the 'Input Curve Speckle Type' setting."
            ),
        )
        automate_context.mark_run_failed(
            f"No '{target_type}' objects found in the trigger model."
        )
        return

    logger.info("Found %d curve objects.", len(curve_objects))

    # ------------------------------------------------------------------
    # 3. Convert Speckle curves → Rhino JSON
    # ------------------------------------------------------------------
    curve_jsons = []
    skipped = []
    for obj in curve_objects:
        rj = _speckle_curve_to_rhino_json(obj)
        if rj is not None:
            curve_jsons.append(rj)
        else:
            skipped.append(obj)

    if skipped:
        automate_context.attach_warning_to_objects(
            category="Conversion",
            affected_objects=skipped,
            message="Could not convert these objects to Rhino curves — they were skipped.",
        )

    if not curve_jsons:
        automate_context.mark_run_failed(
            "All curve objects failed conversion to Rhino format. "
            "Check the curve speckle_type setting or object structure."
        )
        return

    # ------------------------------------------------------------------
    # 4. Connect to Rhino Compute + fetch GH definition
    # ------------------------------------------------------------------
    _setup_compute(function_inputs)

    try:
        gh_bytes = _fetch_gh_definition(function_inputs.grasshopper_definition_url)
    except Exception as exc:
        automate_context.mark_run_exception(
            f"Failed to download Grasshopper definition: {exc}"
        )
        return

    gh_definition = list(gh_bytes)  # compute SDK expects a list of ints

    # ------------------------------------------------------------------
    # 5. Build Grasshopper input trees and run compute
    # ------------------------------------------------------------------
    gh_trees = _build_gh_trees(curve_jsons, function_inputs)

    logger.info("Sending %d curves to Rhino Compute …", len(curve_jsons))
    try:
        gh_result = Grasshopper.EvaluateDefinition(gh_definition, gh_trees)
    except Exception as exc:
        automate_context.mark_run_exception(
            f"Rhino Compute call failed: {exc}"
        )
        return

    # Check for compute-level errors
    if gh_result.get("errors"):
        errors = gh_result["errors"]
        logger.error("Grasshopper errors: %s", errors)
        automate_context.mark_run_failed(
            f"Grasshopper returned errors: {'; '.join(str(e) for e in errors)}"
        )
        return

    if gh_result.get("warnings"):
        logger.warning("Grasshopper warnings: %s", gh_result["warnings"])

    # ------------------------------------------------------------------
    # 6. Parse output geometry → Speckle objects
    # ------------------------------------------------------------------
    panel_objects = _parse_gh_output(gh_result, function_inputs.gh_panel_output_name)

    if not panel_objects:
        automate_context.mark_run_failed(
            f"Grasshopper ran successfully but returned no geometry on output "
            f"'{function_inputs.gh_panel_output_name}'. "
            "Check the GH Output Parameter Name setting."
        )
        return

    logger.info("Generated %d panel objects.", len(panel_objects))

    # ------------------------------------------------------------------
    # 7. Publish panels to the target Speckle model
    # ------------------------------------------------------------------
    root = Base()
    root.elements = panel_objects
    root["sourceModelId"] = automate_context.automation_run_data.triggers[0].payload.model_id
    root["panelType"] = function_inputs.panel_type.value
    root["panelDepth"] = function_inputs.panel_depth
    root["curveCount"] = len(curve_jsons)
    root["panelCount"] = len(panel_objects)

    automate_context.create_new_version_in_project(
        root_object=root,
        model_id=function_inputs.target_model_id,
        version_message=function_inputs.output_version_message,
    )

    # Annotate the source curves as processed
    automate_context.attach_success_to_objects(
        category="Facade Generation",
        affected_objects=curve_objects,
        message=(
            f"Generated {len(panel_objects)} '{function_inputs.panel_type.value}' "
            f"panels from {len(curve_jsons)} curves → "
            f"model '{function_inputs.target_model_id}'"
        ),
        metadata={
            "panelCount": len(panel_objects),
            "curveCount": len(curve_jsons),
            "panelType": function_inputs.panel_type.value,
            "panelDepth": function_inputs.panel_depth,
        },
    )

    automate_context.mark_run_success(
        f"Generated {len(panel_objects)} facade panels from {len(curve_jsons)} curves "
        f"and published to model '{function_inputs.target_model_id}'."
    )


# ---------------------------------------------------------------------------
if __name__ == "__main__":
    execute_automate_function(automate_function, FunctionInputs)
